{
 "title": "Health",
 "time": { "from": "now-3y", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Readiness",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "readiness",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Resting Heart Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "lowest_heart_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"heart\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Cardiovascular Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "yr" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cardiovascular_age\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Readiness Score",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readiness\")\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Resting Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readiness\")\n  |> filter(fn: (r) => r[\"_field\"] == \"resting_heart_rate\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Sleep Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"readiness\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sleep_balance\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Time in Bed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sleep\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_in_bed\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Total Sleep Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sleep\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_sleep_duration\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Time in Bed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sleep\")\n  |> filter(fn: (r) => r[\"_field\"] == \"deep_sleep_duration\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sleep\")\n  |> filter(fn: (r) => r[\"_field\"] == \"light_sleep_duration\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sleep\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rem_sleep_duration\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sleep\")\n  |> filter(fn: (r) => r[\"_field\"] == \"awake_time\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heart",
     "query": "from(bucket: \"oura-sync\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sleep\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "!=", "value": "live" }
     ]
    }
   ]
  },
  {
   "title": "Body Temperature & Blood Oxygen Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "temperature_deviation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "readiness",
     "select": [
      [
       { "params": [ "temperature_deviation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "blood oxygen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spo2",
     "select": [
      [
       { "params": [ "spo2_percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resting Heart Rate & HRV",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "alias": "HRV",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "average_hrv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "average_heart_rate",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "average_heart_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "lowest_heart_rate",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "lowest_heart_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         20
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "lowest_heart_rate::field", "operator": "<", "value": "150" }
     ]
    }
   ]
  },
  {
   "title": "Sleep Phases",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "sleep_algorithm_version::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT moving_average(mean(\"deep_sleep_duration\"), 20) FROM \"sleep\" WHERE (\"type\"::tag = 'long_sleep') AND $timeFilter GROUP BY time(24h), \"sleep_algorithm_version\"::tag fill(null)",
     "select": [
      [
       { "params": [ "deep_sleep_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "long_sleep" }
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "sleep_algorithm_version::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "awake_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "long_sleep" }
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "sleep_algorithm_version::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "light_sleep_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "long_sleep" }
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "sleep_algorithm_version::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "rem_sleep_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "long_sleep" }
     ]
    },
    {
     "alias": "TOTAL",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "sleep_algorithm_version::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "total_sleep_duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "long_sleep" }
     ]
    },
    {
     "alias": "Latency",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "sleep_algorithm_version::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ " * -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type::tag", "operator": "=", "value": "long_sleep" }
     ]
    }
   ]
  },
  {
   "title": "Stress & Recovery",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "alias": "Stress",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stress",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "stress_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Recovery",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stress",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "recovery_high" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Readiness",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "readiness",
     "query": "SELECT mean(\"average_heart_rate\") FROM \"sleep\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  }
 ]
}